export { default as Home } from './Home'
export { default as Search } from './Search'
export { default as Detail } from './Detail'
export { default as Favorites } from './Favorites'
export { default as SplashScreen } from './SplashScreen'
